---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: busybox-drpc-2
  labels:
    app: busybox-sample
spec:
  preferredCluster: "manage-c1"
  drPolicyRef:
    name: odr-policy-east-west-rpo-5m
  placementRef:
    kind: PlacementRule
    name: busybox-placement-2
  pvcSelector:
    matchLabels:
      appname: busybox
