---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc-2
  labels:
    appname: busybox
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "ocs-storagecluster-ceph-rbd"
  resources:
    requests:
      storage: 8Gi
