apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox
  name: busybox-pvc-40
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 18Gi
  storageClassName: ocs-storagecluster-ceph-rbd-mirror
